name: autofix.ci
on:
  pull_request:
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use the latest LTS version of Node.js

      - name: Lint fix
        run: |
          npm ci
          npm run lint:fix

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
