name: " 🧪 Build and Test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node-versions:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x

        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install / build / test
        run: |
          npm install
          npm run build
          npm test

  test-os:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 18.x
        os:
          # - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install / build / test
        run: |
          npm install
          npm run build
          npm test
