name: ' 🔗 Update Dependencies'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: Reference Branch
        default: main
        required: false
  schedule:
    - cron: '0 12 * * 0'

permissions:
  contents: read

jobs:
  update-dependencies:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: "update-dependencies-${{ inputs.ref || 'main' }}"
      REF_BRANCH: ${{ inputs.ref || 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update
        run: |
          npm install
          npm run update-packages

      - name: Lint
        run: |
          npm run lint

      - name: PR Body
        id: body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: 'Update ALL Dependencies'
          path: >-
            package.json
            README.md

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: 'ci: Update ALL Dependencies -- Workflow Bot'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: 'ci: Update ALL Dependencies (${{ env.REF_BRANCH }})'
          body: ${{ steps.body.outputs.body }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
